### ISSUE TITLE
% character is not escaped in book lookup

### ISSUE THREAD

**Issue by STommydx** [chihimng/COMP4111_Project#21]
**Describe the bug**
`%` character is not escaped in LIKE statements in book searching criteria.

**To Reproduce**
1. Login as usual
2. Add the following book
```json
{
            "Title": "Book 25!",
            "Author": "Author",
            "Publisher": "Publisher",
            "Year": "2028"
}
```
3. Search book containing title specified below
`GET localhost:8080/BookManagementService/books?token={{token}}&title=%25`

**Expected behavior**
`204 No Content`

**What actually happens**
`200 OK` with the book returned
```json
{
    "Results": [
        {
            "Title": "Book 25!",
            "Author": "Author",
            "Publisher": "Publisher",
            "Year": 2028,
            "Available": true
        }
    ],
    "FoundBooks": 1
}
```

**Comment by elise-ng** [comment]
Confirmed. Thanks.
