### ISSUE TITLE
Prepared operation is done even the transaction is canceled

### ISSUE THREAD

**Issue by skleeab** [chihimng/COMP4111_Project#24]
### Description
Prepared operation is done even the transaction is canceled.

### How to reproduce
1. Login as usual
2. Add the following book
```
{
        "Title": "Book 1",
        "Author": "First Guy",
        "Publisher": "First Inc.",
        "Year": 2020
}
```
3.  Request a Transaction ID, the sample result is as follow: 
``` 
{
    "Transaction": 219
}
```

4. Prepare a transaction operation as follow: 
```
{
	"Transaction" : 219,
	"Book" : 1,
	"Action": "loan"
}
```

5. Cancel the transaction with id ```219```
```
{
	"Transaction" : 219,
	"Operation" : "cancel"
}
```

6. Loan the book with id ```1```

### Expected results
The server returns ```200 OK```

### What actually happens
The server returns ```400 Bad Request```

**Comment by Camerash** [comment]
Confirmed. Thanks.

**Comment by comp4111ta** [comment]
@skleeab Did you loan the book with a transaction or just loaning the book?
