### ISSUE TITLE
[GET /books] Invalid "sortby" parameter is accepted

### ISSUE THREAD

**Issue by davidtang1006** [chihimng/COMP4111_Project#25]
### Steps to reproduce the issue

1. Log in first.
2. Add the follwing books:
   ```json
   {
       "Title": "Alice in Wonderland",
       "Author": "Lewis Carroll",
       "Publisher": "Macmillan Publishers",
       "Year": 1865
   }
   ```
   ```json
   {
       "Title": "Alice",
       "Author": "Lewis",
       "Publisher": "Mac",
       "Year": 2020
   }
   ```
   ```json
   {
       "Title": "SINoALICE",
       "Author": "SQUARE",
       "Publisher": "ENIX",
       "Year": 2017
   }
   ```
3. Look up book information with `GET /BookManagementService/books?sortby=ids&token=${token}` or `GET /BookManagementService/books?sortby=ids&order=desc&token=${token}`. Note that `ids` is invalid.

### What's the expected result?

Response like `400 Bad Request` to notify the user that something is not right.

### What's the actual result?

Both `GET /BookManagementService/books?sortby=ids&token=${token}` and `GET /BookManagementService/books?sortby=ids&order=desc&token=${token}` give `200 OK` with the following payload:
```json
{
    "Results":[
        {
            "Title":"Alice in Wonderland",
            "Author":"Lewis Carroll",
            "Publisher":"Macmillan Publishers",
            "Year":1865,
            "Available":true
        },
        {
            "Title":"Alice",
            "Author":"Lewis",
            "Publisher":"Mac",
            "Year":2020,
            "Available":true
        },
        {
            "Title":"SINoALICE",
            "Author":"SQUARE",
            "Publisher":"ENIX",
            "Year":2017,
            "Available":true
        }
    ],
    "FoundBooks":3
}
```

**Comment by elise-ng** [comment]
Please cite which part of project spec required this behavior, otherwise will be considered as out-of-spec behavior and invalid. Thanks.

**Comment by davidtang1006** [comment]
The related behaviours are defined in <https://course.cse.ust.hk/comp4111/project.html#5613aed5-cefa-4c9f-935d-71ddaa088aeb>. I think it is better to let @comp4111ta to decide if this is a bug. Previously some bad behaviours are regarded as bugs as well even they are not exactly mentioned in the spec.

**Comment by elise-ng** [comment]
The documented `sortby` feature works as required in our implementation. How to handle other values passing into the parameter is not defined in the spec tho.

**Comment by STommydx** [comment]
Hi,
This issue from our team may be helpful for you guys. https://github.com/STommydx/2020S-COMP4111/issues/18
Such issues were considered invalid.

**Comment by comp4111ta** [comment]
This is not considered a bug
