### ISSUE TITLE
Receiving abnormal responses for bad method requests

### ISSUE THREAD

**Issue by davidtang1006** [chihimng/COMP4111_Project#27]
### Steps to reproduce the issue (1)

- Attempt to log in with `GET /BookManagementService/login` (it should be `POST`) and payload
  ```json
  {
      "Username": "user00001",
      "Password": "pass00001"
  }
  ```

### What's the expected result? (1)

Ideally `405 Method Not Allowed`.

### What's the actual result? (1)

No response is received.

### Steps to reproduce the issue (2)

1. Log in first.
2. Attempt to log out with `POST /BookManagementService/logout?token=${token}` (it should be `GET`).

### What's the expected result? (2)

Ideally `405 Method Not Allowed`.

### What's the actual result? (2)

`200 OK` is received. The corresponding user apparently logs out since subsequent `GET /BookManagementService/logout?token=${token}` returns `400 Bad Request`.

### Steps to reproduce the issue (3)

1. Log in first.
2. Request a transaction ID.
3. Commit a transaction with `GET /BookManagementService/transaction?token=${token}` (it should be `POST`) and payload
   ```txt
   {
       "Transaction": ${transaction},
       "Operation": "commit"
   }
   ```

### What's the expected result? (3)

Ideally `405 Method Not Allowed`.

### What's the actual result? (3)

No response is received.

### Steps to reproduce the issue (4)

1. Log in first.
2. Add a book.
3. Request a transaction ID.
4. Attempt to loan the book with `GET BookManagementService/transaction?token=${token}` (it should be `PUT`) and payload
   ```txt
   {
       "Transaction": ${transaction},
       "Book": ${id},
       "Action": "loan"
   }
   ```

### What's the expected result? (4)

Ideally `405 Method Not Allowed`.

### What's the actual result? (4)

No response is received.

**Comment by elise-ng** [comment]
Rejecting undocumented request is not required in project spec. We will consider this out-of-spec and invalid. Thanks.

**Comment by comp4111ta** [comment]
Undefined Behavior.
