### ISSUE TITLE
[POST /books] Receiving no responses after adding a book with missing/null year

### ISSUE THREAD

**Issue by davidtang1006** [chihimng/COMP4111_Project#28]
1. Log in first.
2. Add a book with `POST /BookManagementService/books?token=${token}` and payload being
   ```json
   {
       "Title": "Alice",
       "Author": "Lewis",
       "Publisher": "Mac"
   }
   ```
   or
   ```json
   {
       "Title": "Alice",
       "Author": "Lewis",
       "Publisher": "Mac",
       "Year": null
   }
   ```

### What's the expected result?

`400 Bad Request`. There are no problems with returning `400 Bad Request` if the title/author/publisher is missing/null though.

### What's the actual result?

No response is received.

**Comment by comp4111ta** [comment]
The server should at least return a response.
