### ISSUE TITLE
[PUT /books] Empty payload request returns "200 OK"

### ISSUE THREAD

**Issue by davidtang1006** [chihimng/COMP4111_Project#29]
### Steps to reproduce the issue

1. Log in first.
2. Add a book.
3. Request with `PUT /BookManagementService/books/${id}?token=${token}` and payload being `{}`.

### What's the expected result?

`400 Bad Request`. There is no problem with returning `400 Bad Request` if the payload is of length zero though.

### What's the actual result?

`200 OK`.

**Comment by comp4111ta** [comment]
Undefined Behavior.
